version: "3"
services:
  app:
    build: .
    container_name: python-app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 3s
      retries: 10

  zap:
    image: zaproxy/zap-stable
    container_name: zap-scanner
    depends_on:
      app:
        condition: service_healthy
    command: >
      zap-baseline.py -t http://app:8000
      -J report_json.json -w report_md.md -r report_html.html -T 5
    volumes:
      - ./zap-report:/zap/wrk